minio:
  endpoint_url: http://172.17.0.1:9001
  access_key: minioadmin
  secret_key: minioadmin

dataset:
  bucket_name: main-bucket
  object_key: data/processed/cleaned_data.csv
  local_path: datas
  


minio:
  endpoint_url: "http://localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"

data:
  bucket: "main-bucket"
  path: "data/processed/cleaned_data.csv"
  original_data: "data/raw/creditcard.csv"