minio:
  endpoint_url: http://10.17.0.243:9000
  access_key: minioadmin
  secret_key: minioadmin

dataset:
  bucket_name: main-bucket
  object_key: data/processed/cleaned_data.csv
  local_path: datas
  
anomalies:
  percentile: 95
  metric: mse

model:
  save_path: /models/autoencoder_model.h5
