# Use a Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY train.py .
COPY lib /app/lib
COPY train_config.yaml /app/

# Define the command to run the script
CMD ["python3", "train.py"]
