minio:
  endpoint_url: http://172.17.0.1:9000
  access_key: minioadmin
  secret_key: minioadmin

data:
  bucket: main-bucket
  original_data: data/processed/cleaned_data.csv


model:
  bucket: main-bucket
  key: models/model.keras
training:
  batch_size: 128
  epochs: 1

anomaly_detection:
  percentile: 95
  metric: 'mse'

evaluation:
  key: data/metrics/evaluation_metrics.json
