minio:
  endpoint_url: http://10.17.0.243:9000
  access_key: minioadmin
  secret_key: minioadmin
  secure: false

# Configuration for the dataset
data:
  bucket: main-bucket
  path: data/processed/cleaned_data.csv

training:
  batch_size: 256
  epochs: 1

model:
  bucket_name: main-bucket
  save_path: /models/autoencoder_model.keras
 

anomaly_detection:
  percentile: 95
  metric: mse


